### ISSUE TITLE
Pushable Items

### ISSUE THREAD

**Issue by jrb0030** [Neoky/Lua_Roguelite#1]
When I add an "item" to a scene, the item is pushable, even if I set the pushable flag to "false".  I tried using an "object" in its place but then the character just walked over the thing.  Basically I am trying to add an item which is not passable or pushable by the character.

**Comment by smm0034** [comment]
The Init function in itemClass makes all objects with the "decor" tag pushable during initialization, That's probably why you can push everything around

I'm not sure why a normal object would not work, though, since its properties should be transferred directly from the object list and attached to a newImage. The interactionCheck function in arrows doesn't even check for a tag either. It just checks if the object is pushable. It should work the same way as an item object in that situation.

Unfortunately, I can't test this out right now because I was just taking a look at the code while taking a break from work.

**Comment by jrb0030** [comment]
I updated itemClass and map to correct assign the passable and pushable attributes to the items as they are set in the scene files.  I discovered that when we set the arrows and move the player we check the passable attribute of the tiles in mapArray but not of the objects in the objectArray. For now, I modified interactionCheck in arrows to verify if the player is being moved into a non-passable item.  If an item is non-passable and non-pushable, the player will not be moved into the tile of the item.
